# Prediction for Survival of the Titanic desaster with Catboost Model

## 1. Importing the libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from catboost import CatBoostClassifier

## 2. Reading the datasets 

In [2]:
train = pd.read_csv('../00_data/train.csv')
test = pd.read_csv('../00_data/test.csv')

## 3. Exploring the datasets

### 3.1 Training set

In [3]:
print(train.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [4]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [5]:
print(train.isna().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


### 3.2 Test set

In [6]:
print(test.head())

   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S  


In [7]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB
None


In [8]:
print(test.isna().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


## 4. Preprocessing

### 4.1 Drop unnecessary columns

#### 4.1.1 Training set

In [9]:
print(train['Ticket'])
print(train['Ticket'].nunique())

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...       
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object
681


Drop PassengerId, Name, Ticket and Embarked as these features don't supply useful information for the prediction of survival.
Drop Cabin, too, as there are too many missing values.

In [10]:
train.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked'], inplace=True)

#### 4.1.2 Test set

For the test set we keep the PassengerId, as we need it for the construction of the result dataframe containing the predictions for survival of a passenger made by the model.

In [11]:
test.drop(columns=['Name', 'Ticket', 'Cabin', 'Embarked'], inplace=True)

### 4.2 Splitting the Training set in train and test data

In [12]:
train_train, train_test = train_test_split(train, test_size=0.2, random_state=0)

### 4.3 Creating X and y for model development

In [13]:
train_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare
140         0       3  female   NaN      0      2  15.2458
439         0       2    male  31.0      0      0  10.5000
817         0       2    male  31.0      1      1  37.0042
378         0       3    male  20.0      0      0   4.0125
491         0       3    male  21.0      0      0   7.2500

In [14]:
X_train = train_train.iloc[:, 1:].values
y_train = train_train.iloc[:, 0].values

In [15]:
print(X_train)
print(y_train)

[[3 'female' nan 0 2 15.2458]
 [2 'male' 31.0 0 0 10.5]
 [2 'male' 31.0 1 1 37.0042]
 ...
 [3 'male' nan 0 0 7.7333]
 [3 'female' 36.0 1 0 17.4]
 [2 'male' 60.0 1 1 39.0]]
[0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0
 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0
 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0
 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0
 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1
 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0
 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1
 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0
 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 0
 0 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1
 1 

In [16]:
X_test = train_test.iloc[:, 1:].values
y_test = train_test.iloc[:, 0].values

In [17]:
print(X_test)
print(y_test)

[[3 'male' nan 0 0 14.4583]
 [3 'male' nan 0 0 7.55]
 [3 'male' 7.0 4 1 29.125]
 ...
 [1 'female' 31.0 1 0 113.275]
 [3 'male' 23.0 0 0 7.8542]
 [3 'male' 19.0 0 0 8.05]]
[0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0
 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0
 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1
 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0]


### 4.4 Creating X as input for prediction

In [18]:
print(test.head())

   PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare
0          892       3    male  34.5      0      0   7.8292
1          893       3  female  47.0      1      0   7.0000
2          894       2    male  62.0      0      0   9.6875
3          895       3    male  27.0      0      0   8.6625
4          896       3  female  22.0      1      1  12.2875


In [19]:
X_pred = test.iloc[:, 1:].values

In [20]:
print(X_pred)

[[3 'male' 34.5 0 0 7.8292]
 [3 'female' 47.0 1 0 7.0]
 [2 'male' 62.0 0 0 9.6875]
 ...
 [3 'male' 38.5 0 0 7.25]
 [3 'male' nan 0 0 8.05]
 [3 'male' nan 1 1 22.3583]]


### 4.5 Handle missing data 

#### 4.5.1 Training set (model development)

In [21]:
print(train_train.isna().sum())

Survived      0
Pclass        0
Sex           0
Age         141
SibSp         0
Parch         0
Fare          0
dtype: int64


##### Calculate treshold for missing values

In [22]:
treshold = len(train_train) * 0.05
print(treshold)
print(len(train_train))

35.6
712


As it is already obvious, the number of missing values in Age is far above the treshold so we cannot simply drop them. 

We have now two options: 
- drop feature Age as there are many missing values in it
- handle missing data by imputing mean e.g.

First we try building the model with feature Age and imputed values. 

##### Keep Age and impute missing values

In [23]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(np.reshape(X_train[:, 2], (len(X_train[:, 2]), 1)))
X_train[:, 2] = imputer.transform(np.reshape(X_train[:, 2], (len(X_train[:, 2]), 1))).reshape(-1)

In [24]:
print(X_train)

[[3 'female' 24.0 0 2 15.2458]
 [2 'male' 31.0 0 0 10.5]
 [2 'male' 31.0 1 1 37.0042]
 ...
 [3 'male' 24.0 0 0 7.7333]
 [3 'female' 36.0 1 0 17.4]
 [2 'male' 60.0 1 1 39.0]]


#### 4.5.2 Test set (model development)

In [25]:
print(train_test.isna().sum())

Survived     0
Pclass       0
Sex          0
Age         36
SibSp        0
Parch        0
Fare         0
dtype: int64


In [26]:
X_test[:, 2] = imputer.transform(np.reshape(X_test[:, 2], (len(X_test[:, 2]), 1))).reshape(-1)

In [27]:
print(X_test)

[[3 'male' 24.0 0 0 14.4583]
 [3 'male' 24.0 0 0 7.55]
 [3 'male' 7.0 4 1 29.125]
 ...
 [1 'female' 31.0 1 0 113.275]
 [3 'male' 23.0 0 0 7.8542]
 [3 'male' 19.0 0 0 8.05]]


#### 4.5.3 Test set (test set to predict)

In [28]:
print(test.isna().sum())

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
dtype: int64


Here we have one additional column with missing values in Fare.

##### Calculate treshold for missing values

In [29]:
treshold = len(test) * 0.05
print(treshold)
print(len(test))

20.900000000000002
418


The missing value in Fare is below the treshold and the observation could be dropped. But as this observation belongs to the test set to predict, we have to deal with it and impute the missing value instead. The missing values in Age are filled by the imputer used for the training set.

##### Impute missing values for Age

In [30]:
X_pred[:, 2] = imputer.transform(np.reshape(X_pred[:, 2], (len(X_pred[:, 2]), 1))).reshape(-1)

In [31]:
print(X_pred)

[[3 'male' 34.5 0 0 7.8292]
 [3 'female' 47.0 1 0 7.0]
 [2 'male' 62.0 0 0 9.6875]
 ...
 [3 'male' 38.5 0 0 7.25]
 [3 'male' 24.0 0 0 8.05]
 [3 'male' 24.0 1 1 22.3583]]


In [32]:
##### Impute missing values for Fare

In [33]:
imputer_fare = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_fare.fit(np.reshape(X_pred[:, 5], (len(X_pred[:, 5]), 1)))
X_pred[:, 5] = imputer.transform(np.reshape(X_pred[:, 5], (len(X_pred[:, 5]), 1))).reshape(-1)

### 4.6 Encode categorical values

#### 4.6.1 Training set (model development)

In [34]:
print(X_train)

[[3 'female' 24.0 0 2 15.2458]
 [2 'male' 31.0 0 0 10.5]
 [2 'male' 31.0 1 1 37.0042]
 ...
 [3 'male' 24.0 0 0 7.7333]
 [3 'female' 36.0 1 0 17.4]
 [2 'male' 60.0 1 1 39.0]]


Encode values in PClass (col 0) and Sex (col 1).

In [35]:
ct_X = ColumnTransformer(transformers=[('encoder', OneHotEncoder(handle_unknown='ignore'), [0, 1])], remainder='passthrough')
ct_X.fit(X_train)
X_train = ct_X.transform(X_train)

In [36]:
print(X_train)

[[0.0 0.0 1.0 ... 0 2 15.2458]
 [0.0 1.0 0.0 ... 0 0 10.5]
 [0.0 1.0 0.0 ... 1 1 37.0042]
 ...
 [0.0 0.0 1.0 ... 0 0 7.7333]
 [0.0 0.0 1.0 ... 1 0 17.4]
 [0.0 1.0 0.0 ... 1 1 39.0]]


#### 4.6.2 Test set (model input)

In [37]:
X_test = ct_X.transform(X_test)

In [38]:
print(X_test)

[[0.0 0.0 1.0 ... 0 0 14.4583]
 [0.0 0.0 1.0 ... 0 0 7.55]
 [0.0 0.0 1.0 ... 4 1 29.125]
 ...
 [1.0 0.0 0.0 ... 1 0 113.275]
 [0.0 0.0 1.0 ... 0 0 7.8542]
 [0.0 0.0 1.0 ... 0 0 8.05]]


#### 4.6.3 Test set (test set to predict)

In [39]:
X_pred = ct_X.transform(X_pred)

In [40]:
print(X_pred)

[[0.0 0.0 1.0 ... 0 0 7.8292]
 [0.0 0.0 1.0 ... 1 0 7.0]
 [0.0 1.0 0.0 ... 0 0 9.6875]
 ...
 [0.0 0.0 1.0 ... 0 0 7.25]
 [0.0 0.0 1.0 ... 0 0 8.05]
 [0.0 0.0 1.0 ... 1 1 22.3583]]


### 4.7 Feature Scaling

#### 4.7.1 Training set (model development)

In [41]:
sc = StandardScaler()
X_train[:, 2:] = sc.fit_transform(X_train[:, 2:])

In [42]:
print(X_train)

[[0.0 0.0 0.8932971498777942 ... -0.46445233851359824 1.9592640285249252
  -0.3316790433256366]
 [0.0 1.0 -1.119448327062046 ... -0.46445233851359824 -0.4774101868632787
  -0.4264054204191258]
 [0.0 1.0 -1.119448327062046 ... 0.41270963767123453 0.7409269208308232
  0.10261957931985559]
 ...
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.4816288743161625]
 [0.0 0.0 0.8932971498777942 ... 0.41270963767123453 -0.4774101868632787
  -0.2886811164145163]
 [0.0 1.0 -1.119448327062046 ... 0.41270963767123453 0.7409269208308232
  0.1424558352520875]]


#### 4.7.2 Test set (model development)

In [43]:
X_test[:, 2:] = sc.transform(X_test[:, 2:])

In [44]:
print(X_test)

[[0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.3473975780218148]
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.485287550392111]
 [0.0 0.0 0.8932971498777942 ... 3.0441955662257327 0.7409269208308232
  -0.05464959982697327]
 ...
 [1.0 0.0 -1.119448327062046 ... 0.41270963767123453 -0.4774101868632787
  1.6249881077075041]
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.4792157049894731]
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.4753075283627915]]


#### 4.7.3 Test set (test set to predict)

In [45]:
X_pred[:, 2:] = sc.transform(X_pred[:, 2:])

In [46]:
print(X_pred)

[[0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.479714706090939]
 [0.0 0.0 0.8932971498777942 ... 0.41270963767123453 -0.4774101868632787
  -0.49626557462436255]
 [0.0 1.0 -1.119448327062046 ... -0.46445233851359824 -0.4774101868632787
  -0.44262295621677006]
 ...
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.49127556360970276]
 [0.0 0.0 0.8932971498777942 ... -0.46445233851359824 -0.4774101868632787
  -0.4753075283627915]
 [0.0 0.0 0.8932971498777942 ... 0.41270963767123453 0.7409269208308232
  -0.1897132299585662]]


### 4.8 Build the CatBoost model

In [47]:
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

Learning rate set to 0.008911
0:	learn: 0.6867834	total: 150ms	remaining: 2m 29s
1:	learn: 0.6806759	total: 160ms	remaining: 1m 19s
2:	learn: 0.6759231	total: 169ms	remaining: 56.3s
3:	learn: 0.6704188	total: 176ms	remaining: 43.8s
4:	learn: 0.6660387	total: 180ms	remaining: 35.8s
5:	learn: 0.6610879	total: 185ms	remaining: 30.7s
6:	learn: 0.6558998	total: 190ms	remaining: 27s
7:	learn: 0.6511135	total: 194ms	remaining: 24s
8:	learn: 0.6461282	total: 197ms	remaining: 21.7s
9:	learn: 0.6408987	total: 201ms	remaining: 19.9s
10:	learn: 0.6366610	total: 203ms	remaining: 18.3s
11:	learn: 0.6327431	total: 205ms	remaining: 16.9s
12:	learn: 0.6287332	total: 207ms	remaining: 15.7s
13:	learn: 0.6247303	total: 209ms	remaining: 14.8s
14:	learn: 0.6212176	total: 211ms	remaining: 13.8s
15:	learn: 0.6165896	total: 214ms	remaining: 13.1s
16:	learn: 0.6124960	total: 216ms	remaining: 12.5s
17:	learn: 0.6081248	total: 218ms	remaining: 11.9s
18:	learn: 0.6038448	total: 220ms	remaining: 11.4s
19:	learn: 0.

208:	learn: 0.3900579	total: 663ms	remaining: 2.51s
209:	learn: 0.3897264	total: 665ms	remaining: 2.5s
210:	learn: 0.3895054	total: 668ms	remaining: 2.5s
211:	learn: 0.3894028	total: 670ms	remaining: 2.49s
212:	learn: 0.3891462	total: 672ms	remaining: 2.48s
213:	learn: 0.3887921	total: 674ms	remaining: 2.48s
214:	learn: 0.3886130	total: 677ms	remaining: 2.47s
215:	learn: 0.3884294	total: 679ms	remaining: 2.46s
216:	learn: 0.3882635	total: 681ms	remaining: 2.46s
217:	learn: 0.3880472	total: 684ms	remaining: 2.45s
218:	learn: 0.3876608	total: 686ms	remaining: 2.45s
219:	learn: 0.3871187	total: 689ms	remaining: 2.44s
220:	learn: 0.3866065	total: 691ms	remaining: 2.44s
221:	learn: 0.3864192	total: 694ms	remaining: 2.43s
222:	learn: 0.3862730	total: 696ms	remaining: 2.42s
223:	learn: 0.3860444	total: 698ms	remaining: 2.42s
224:	learn: 0.3858143	total: 701ms	remaining: 2.41s
225:	learn: 0.3855244	total: 703ms	remaining: 2.41s
226:	learn: 0.3853132	total: 705ms	remaining: 2.4s
227:	learn: 0.3

417:	learn: 0.3538874	total: 1.17s	remaining: 1.63s
418:	learn: 0.3538028	total: 1.17s	remaining: 1.63s
419:	learn: 0.3536224	total: 1.18s	remaining: 1.62s
420:	learn: 0.3535221	total: 1.18s	remaining: 1.62s
421:	learn: 0.3533918	total: 1.18s	remaining: 1.62s
422:	learn: 0.3533485	total: 1.18s	remaining: 1.61s
423:	learn: 0.3532373	total: 1.19s	remaining: 1.61s
424:	learn: 0.3532077	total: 1.19s	remaining: 1.61s
425:	learn: 0.3531141	total: 1.19s	remaining: 1.6s
426:	learn: 0.3529968	total: 1.21s	remaining: 1.62s
427:	learn: 0.3528739	total: 1.21s	remaining: 1.61s
428:	learn: 0.3528658	total: 1.21s	remaining: 1.61s
429:	learn: 0.3525159	total: 1.21s	remaining: 1.61s
430:	learn: 0.3522045	total: 1.22s	remaining: 1.6s
431:	learn: 0.3519352	total: 1.22s	remaining: 1.6s
432:	learn: 0.3517724	total: 1.22s	remaining: 1.6s
433:	learn: 0.3517302	total: 1.22s	remaining: 1.59s
434:	learn: 0.3516914	total: 1.23s	remaining: 1.59s
435:	learn: 0.3515629	total: 1.23s	remaining: 1.59s
436:	learn: 0.35

607:	learn: 0.3327955	total: 1.67s	remaining: 1.08s
608:	learn: 0.3327201	total: 1.68s	remaining: 1.07s
609:	learn: 0.3326553	total: 1.68s	remaining: 1.07s
610:	learn: 0.3324339	total: 1.68s	remaining: 1.07s
611:	learn: 0.3323407	total: 1.68s	remaining: 1.07s
612:	learn: 0.3322621	total: 1.69s	remaining: 1.06s
613:	learn: 0.3322052	total: 1.69s	remaining: 1.06s
614:	learn: 0.3321260	total: 1.69s	remaining: 1.06s
615:	learn: 0.3320761	total: 1.69s	remaining: 1.05s
616:	learn: 0.3319851	total: 1.7s	remaining: 1.05s
617:	learn: 0.3319091	total: 1.7s	remaining: 1.05s
618:	learn: 0.3317639	total: 1.7s	remaining: 1.05s
619:	learn: 0.3317042	total: 1.7s	remaining: 1.04s
620:	learn: 0.3314399	total: 1.71s	remaining: 1.04s
621:	learn: 0.3312437	total: 1.71s	remaining: 1.04s
622:	learn: 0.3311651	total: 1.71s	remaining: 1.03s
623:	learn: 0.3309791	total: 1.71s	remaining: 1.03s
624:	learn: 0.3308883	total: 1.72s	remaining: 1.03s
625:	learn: 0.3308477	total: 1.72s	remaining: 1.03s
626:	learn: 0.33

802:	learn: 0.3135191	total: 2.16s	remaining: 530ms
803:	learn: 0.3134476	total: 2.16s	remaining: 527ms
804:	learn: 0.3133592	total: 2.17s	remaining: 525ms
805:	learn: 0.3132311	total: 2.17s	remaining: 522ms
806:	learn: 0.3130701	total: 2.17s	remaining: 519ms
807:	learn: 0.3129699	total: 2.17s	remaining: 516ms
808:	learn: 0.3128638	total: 2.17s	remaining: 513ms
809:	learn: 0.3126994	total: 2.18s	remaining: 511ms
810:	learn: 0.3126947	total: 2.18s	remaining: 508ms
811:	learn: 0.3126477	total: 2.18s	remaining: 505ms
812:	learn: 0.3125805	total: 2.18s	remaining: 502ms
813:	learn: 0.3123865	total: 2.19s	remaining: 499ms
814:	learn: 0.3123438	total: 2.19s	remaining: 497ms
815:	learn: 0.3123031	total: 2.19s	remaining: 494ms
816:	learn: 0.3121712	total: 2.19s	remaining: 491ms
817:	learn: 0.3120992	total: 2.19s	remaining: 488ms
818:	learn: 0.3120501	total: 2.2s	remaining: 486ms
819:	learn: 0.3119796	total: 2.2s	remaining: 483ms
820:	learn: 0.3118527	total: 2.2s	remaining: 480ms
821:	learn: 0.3

965:	learn: 0.2974140	total: 2.54s	remaining: 89.5ms
966:	learn: 0.2973329	total: 2.55s	remaining: 86.9ms
967:	learn: 0.2970516	total: 2.55s	remaining: 84.3ms
968:	learn: 0.2968480	total: 2.55s	remaining: 81.6ms
969:	learn: 0.2968114	total: 2.55s	remaining: 79ms
970:	learn: 0.2967588	total: 2.56s	remaining: 76.3ms
971:	learn: 0.2965991	total: 2.56s	remaining: 73.7ms
972:	learn: 0.2965343	total: 2.56s	remaining: 71ms
973:	learn: 0.2965104	total: 2.56s	remaining: 68.4ms
974:	learn: 0.2964501	total: 2.56s	remaining: 65.8ms
975:	learn: 0.2964041	total: 2.57s	remaining: 63.1ms
976:	learn: 0.2963643	total: 2.57s	remaining: 60.5ms
977:	learn: 0.2963157	total: 2.57s	remaining: 57.8ms
978:	learn: 0.2962694	total: 2.57s	remaining: 55.2ms
979:	learn: 0.2962046	total: 2.58s	remaining: 52.6ms
980:	learn: 0.2961148	total: 2.58s	remaining: 49.9ms
981:	learn: 0.2959945	total: 2.58s	remaining: 47.3ms
982:	learn: 0.2959740	total: 2.58s	remaining: 44.7ms
983:	learn: 0.2958378	total: 2.58s	remaining: 42ms

### 4.9. Predict Test set (model development )

In [48]:
y_model_pred = classifier.predict(X_test)

In [49]:
print(np.concatenate((y_model_pred.reshape(len(y_model_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

### 4.10. Print Confusion Matrix

In [50]:
print(confusion_matrix(y_test, y_model_pred))

[[100  10]
 [ 20  49]]


In [51]:
print(accuracy_score(y_test, y_model_pred) * 100)

83.24022346368714


### 4.11. Applying k-Fold Cross Validation

In [52]:
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.008515
0:	learn: 0.6889675	total: 4.78ms	remaining: 4.77s
1:	learn: 0.6844953	total: 8.43ms	remaining: 4.21s
2:	learn: 0.6792068	total: 13.2ms	remaining: 4.38s
3:	learn: 0.6740307	total: 17.7ms	remaining: 4.4s
4:	learn: 0.6688075	total: 21ms	remaining: 4.18s
5:	learn: 0.6639394	total: 23.8ms	remaining: 3.95s
6:	learn: 0.6590574	total: 27ms	remaining: 3.83s
7:	learn: 0.6544640	total: 29.9ms	remaining: 3.7s
8:	learn: 0.6495864	total: 32.2ms	remaining: 3.54s
9:	learn: 0.6446331	total: 34.4ms	remaining: 3.41s
10:	learn: 0.6412601	total: 36.2ms	remaining: 3.26s
11:	learn: 0.6374156	total: 38.1ms	remaining: 3.14s
12:	learn: 0.6334537	total: 40.2ms	remaining: 3.05s
13:	learn: 0.6295359	total: 42.7ms	remaining: 3.01s
14:	learn: 0.6261068	total: 44.5ms	remaining: 2.92s
15:	learn: 0.6227472	total: 46ms	remaining: 2.83s
16:	learn: 0.6204538	total: 47.3ms	remaining: 2.73s
17:	learn: 0.6160479	total: 49.5ms	remaining: 2.7s
18:	learn: 0.6120052	total: 51.7ms	remaining: 2.67s
1

183:	learn: 0.4019998	total: 440ms	remaining: 1.95s
184:	learn: 0.4016809	total: 442ms	remaining: 1.95s
185:	learn: 0.4011101	total: 444ms	remaining: 1.94s
186:	learn: 0.4007340	total: 446ms	remaining: 1.94s
187:	learn: 0.4004042	total: 449ms	remaining: 1.94s
188:	learn: 0.4000968	total: 451ms	remaining: 1.93s
189:	learn: 0.3998103	total: 454ms	remaining: 1.93s
190:	learn: 0.3993966	total: 456ms	remaining: 1.93s
191:	learn: 0.3988271	total: 458ms	remaining: 1.93s
192:	learn: 0.3983386	total: 461ms	remaining: 1.93s
193:	learn: 0.3981301	total: 463ms	remaining: 1.92s
194:	learn: 0.3978918	total: 466ms	remaining: 1.92s
195:	learn: 0.3975643	total: 470ms	remaining: 1.93s
196:	learn: 0.3971520	total: 472ms	remaining: 1.92s
197:	learn: 0.3968773	total: 474ms	remaining: 1.92s
198:	learn: 0.3965500	total: 477ms	remaining: 1.92s
199:	learn: 0.3962332	total: 479ms	remaining: 1.92s
200:	learn: 0.3958874	total: 481ms	remaining: 1.91s
201:	learn: 0.3955411	total: 483ms	remaining: 1.91s
202:	learn: 

346:	learn: 0.3640216	total: 810ms	remaining: 1.52s
347:	learn: 0.3638035	total: 813ms	remaining: 1.52s
348:	learn: 0.3637732	total: 814ms	remaining: 1.52s
349:	learn: 0.3636358	total: 817ms	remaining: 1.52s
350:	learn: 0.3634990	total: 819ms	remaining: 1.51s
351:	learn: 0.3630898	total: 821ms	remaining: 1.51s
352:	learn: 0.3630876	total: 823ms	remaining: 1.51s
353:	learn: 0.3627500	total: 825ms	remaining: 1.51s
354:	learn: 0.3624808	total: 828ms	remaining: 1.5s
355:	learn: 0.3624012	total: 830ms	remaining: 1.5s
356:	learn: 0.3621888	total: 832ms	remaining: 1.5s
357:	learn: 0.3620694	total: 835ms	remaining: 1.5s
358:	learn: 0.3619381	total: 837ms	remaining: 1.49s
359:	learn: 0.3618126	total: 840ms	remaining: 1.49s
360:	learn: 0.3616364	total: 842ms	remaining: 1.49s
361:	learn: 0.3615919	total: 845ms	remaining: 1.49s
362:	learn: 0.3614465	total: 847ms	remaining: 1.49s
363:	learn: 0.3613093	total: 849ms	remaining: 1.48s
364:	learn: 0.3611720	total: 851ms	remaining: 1.48s
365:	learn: 0.36

506:	learn: 0.3433293	total: 1.18s	remaining: 1.15s
507:	learn: 0.3432050	total: 1.18s	remaining: 1.14s
508:	learn: 0.3430403	total: 1.18s	remaining: 1.14s
509:	learn: 0.3430237	total: 1.19s	remaining: 1.14s
510:	learn: 0.3429221	total: 1.19s	remaining: 1.14s
511:	learn: 0.3427256	total: 1.19s	remaining: 1.13s
512:	learn: 0.3426383	total: 1.19s	remaining: 1.13s
513:	learn: 0.3425833	total: 1.2s	remaining: 1.13s
514:	learn: 0.3425556	total: 1.2s	remaining: 1.13s
515:	learn: 0.3422990	total: 1.2s	remaining: 1.13s
516:	learn: 0.3422321	total: 1.2s	remaining: 1.12s
517:	learn: 0.3421823	total: 1.2s	remaining: 1.12s
518:	learn: 0.3418491	total: 1.21s	remaining: 1.12s
519:	learn: 0.3416781	total: 1.21s	remaining: 1.12s
520:	learn: 0.3416353	total: 1.21s	remaining: 1.11s
521:	learn: 0.3413057	total: 1.21s	remaining: 1.11s
522:	learn: 0.3412808	total: 1.22s	remaining: 1.11s
523:	learn: 0.3412169	total: 1.22s	remaining: 1.11s
524:	learn: 0.3410257	total: 1.22s	remaining: 1.1s
525:	learn: 0.3409

708:	learn: 0.3216824	total: 1.64s	remaining: 672ms
709:	learn: 0.3215562	total: 1.64s	remaining: 670ms
710:	learn: 0.3215286	total: 1.64s	remaining: 668ms
711:	learn: 0.3214762	total: 1.64s	remaining: 665ms
712:	learn: 0.3214254	total: 1.65s	remaining: 663ms
713:	learn: 0.3213739	total: 1.65s	remaining: 661ms
714:	learn: 0.3212946	total: 1.65s	remaining: 659ms
715:	learn: 0.3212551	total: 1.65s	remaining: 656ms
716:	learn: 0.3210965	total: 1.66s	remaining: 654ms
717:	learn: 0.3210763	total: 1.66s	remaining: 652ms
718:	learn: 0.3210013	total: 1.66s	remaining: 650ms
719:	learn: 0.3208575	total: 1.67s	remaining: 648ms
720:	learn: 0.3208401	total: 1.67s	remaining: 646ms
721:	learn: 0.3208169	total: 1.67s	remaining: 644ms
722:	learn: 0.3207495	total: 1.67s	remaining: 641ms
723:	learn: 0.3205190	total: 1.68s	remaining: 639ms
724:	learn: 0.3203717	total: 1.68s	remaining: 637ms
725:	learn: 0.3201857	total: 1.68s	remaining: 635ms
726:	learn: 0.3200694	total: 1.68s	remaining: 633ms
727:	learn: 

913:	learn: 0.3012847	total: 2.15s	remaining: 202ms
914:	learn: 0.3011953	total: 2.15s	remaining: 200ms
915:	learn: 0.3011490	total: 2.15s	remaining: 197ms
916:	learn: 0.3010974	total: 2.15s	remaining: 195ms
917:	learn: 0.3009982	total: 2.15s	remaining: 193ms
918:	learn: 0.3007739	total: 2.16s	remaining: 190ms
919:	learn: 0.3007309	total: 2.16s	remaining: 188ms
920:	learn: 0.3006024	total: 2.16s	remaining: 186ms
921:	learn: 0.3005161	total: 2.17s	remaining: 183ms
922:	learn: 0.3003787	total: 2.17s	remaining: 181ms
923:	learn: 0.3001887	total: 2.17s	remaining: 179ms
924:	learn: 0.3001254	total: 2.17s	remaining: 176ms
925:	learn: 0.3000738	total: 2.18s	remaining: 174ms
926:	learn: 0.2999825	total: 2.18s	remaining: 172ms
927:	learn: 0.2998109	total: 2.18s	remaining: 169ms
928:	learn: 0.2997693	total: 2.18s	remaining: 167ms
929:	learn: 0.2997016	total: 2.19s	remaining: 165ms
930:	learn: 0.2995812	total: 2.19s	remaining: 162ms
931:	learn: 0.2995369	total: 2.19s	remaining: 160ms
932:	learn: 

72:	learn: 0.4781726	total: 165ms	remaining: 2.09s
73:	learn: 0.4763489	total: 167ms	remaining: 2.09s
74:	learn: 0.4750866	total: 169ms	remaining: 2.08s
75:	learn: 0.4736720	total: 171ms	remaining: 2.08s
76:	learn: 0.4721914	total: 173ms	remaining: 2.08s
77:	learn: 0.4714678	total: 175ms	remaining: 2.07s
78:	learn: 0.4697338	total: 178ms	remaining: 2.08s
79:	learn: 0.4690717	total: 180ms	remaining: 2.07s
80:	learn: 0.4677738	total: 183ms	remaining: 2.07s
81:	learn: 0.4664560	total: 186ms	remaining: 2.08s
82:	learn: 0.4648568	total: 188ms	remaining: 2.08s
83:	learn: 0.4635314	total: 191ms	remaining: 2.08s
84:	learn: 0.4624487	total: 194ms	remaining: 2.09s
85:	learn: 0.4613091	total: 196ms	remaining: 2.09s
86:	learn: 0.4605591	total: 198ms	remaining: 2.08s
87:	learn: 0.4593875	total: 201ms	remaining: 2.08s
88:	learn: 0.4583780	total: 203ms	remaining: 2.08s
89:	learn: 0.4568408	total: 206ms	remaining: 2.08s
90:	learn: 0.4554064	total: 211ms	remaining: 2.1s
91:	learn: 0.4543014	total: 213m

238:	learn: 0.3773806	total: 544ms	remaining: 1.73s
239:	learn: 0.3772230	total: 547ms	remaining: 1.73s
240:	learn: 0.3770476	total: 549ms	remaining: 1.73s
241:	learn: 0.3767883	total: 551ms	remaining: 1.73s
242:	learn: 0.3765140	total: 553ms	remaining: 1.72s
243:	learn: 0.3763366	total: 556ms	remaining: 1.72s
244:	learn: 0.3760348	total: 559ms	remaining: 1.72s
245:	learn: 0.3757769	total: 562ms	remaining: 1.72s
246:	learn: 0.3753964	total: 564ms	remaining: 1.72s
247:	learn: 0.3751127	total: 566ms	remaining: 1.72s
248:	learn: 0.3750059	total: 568ms	remaining: 1.71s
249:	learn: 0.3748225	total: 570ms	remaining: 1.71s
250:	learn: 0.3745493	total: 573ms	remaining: 1.71s
251:	learn: 0.3743376	total: 575ms	remaining: 1.71s
252:	learn: 0.3742728	total: 577ms	remaining: 1.7s
253:	learn: 0.3741091	total: 579ms	remaining: 1.7s
254:	learn: 0.3737829	total: 581ms	remaining: 1.7s
255:	learn: 0.3734686	total: 583ms	remaining: 1.69s
256:	learn: 0.3733388	total: 586ms	remaining: 1.69s
257:	learn: 0.3

421:	learn: 0.3454911	total: 1.01s	remaining: 1.39s
422:	learn: 0.3452849	total: 1.02s	remaining: 1.39s
423:	learn: 0.3452586	total: 1.02s	remaining: 1.39s
424:	learn: 0.3451358	total: 1.02s	remaining: 1.38s
425:	learn: 0.3450012	total: 1.02s	remaining: 1.38s
426:	learn: 0.3448640	total: 1.03s	remaining: 1.38s
427:	learn: 0.3447756	total: 1.03s	remaining: 1.38s
428:	learn: 0.3446599	total: 1.03s	remaining: 1.37s
429:	learn: 0.3446114	total: 1.03s	remaining: 1.37s
430:	learn: 0.3445714	total: 1.03s	remaining: 1.37s
431:	learn: 0.3445664	total: 1.04s	remaining: 1.36s
432:	learn: 0.3445192	total: 1.04s	remaining: 1.36s
433:	learn: 0.3443434	total: 1.04s	remaining: 1.36s
434:	learn: 0.3442814	total: 1.04s	remaining: 1.35s
435:	learn: 0.3442530	total: 1.04s	remaining: 1.35s
436:	learn: 0.3440947	total: 1.05s	remaining: 1.35s
437:	learn: 0.3439879	total: 1.05s	remaining: 1.35s
438:	learn: 0.3438475	total: 1.05s	remaining: 1.34s
439:	learn: 0.3437954	total: 1.05s	remaining: 1.34s
440:	learn: 

587:	learn: 0.3268342	total: 1.4s	remaining: 978ms
588:	learn: 0.3267525	total: 1.4s	remaining: 976ms
589:	learn: 0.3266455	total: 1.4s	remaining: 973ms
590:	learn: 0.3265789	total: 1.4s	remaining: 971ms
591:	learn: 0.3265477	total: 1.41s	remaining: 969ms
592:	learn: 0.3265140	total: 1.41s	remaining: 966ms
593:	learn: 0.3264234	total: 1.41s	remaining: 964ms
594:	learn: 0.3262874	total: 1.41s	remaining: 962ms
595:	learn: 0.3262430	total: 1.42s	remaining: 960ms
596:	learn: 0.3261127	total: 1.42s	remaining: 958ms
597:	learn: 0.3259645	total: 1.42s	remaining: 956ms
598:	learn: 0.3258970	total: 1.42s	remaining: 953ms
599:	learn: 0.3258804	total: 1.43s	remaining: 951ms
600:	learn: 0.3258016	total: 1.43s	remaining: 948ms
601:	learn: 0.3255881	total: 1.43s	remaining: 946ms
602:	learn: 0.3255058	total: 1.43s	remaining: 943ms
603:	learn: 0.3253865	total: 1.44s	remaining: 941ms
604:	learn: 0.3252749	total: 1.44s	remaining: 939ms
605:	learn: 0.3251384	total: 1.44s	remaining: 936ms
606:	learn: 0.32

748:	learn: 0.3113065	total: 1.77s	remaining: 592ms
749:	learn: 0.3112396	total: 1.77s	remaining: 590ms
750:	learn: 0.3110969	total: 1.77s	remaining: 587ms
751:	learn: 0.3110710	total: 1.77s	remaining: 585ms
752:	learn: 0.3108406	total: 1.78s	remaining: 583ms
753:	learn: 0.3107510	total: 1.78s	remaining: 580ms
754:	learn: 0.3106519	total: 1.78s	remaining: 578ms
755:	learn: 0.3105331	total: 1.78s	remaining: 576ms
756:	learn: 0.3102743	total: 1.79s	remaining: 573ms
757:	learn: 0.3100456	total: 1.79s	remaining: 571ms
758:	learn: 0.3098578	total: 1.79s	remaining: 569ms
759:	learn: 0.3097495	total: 1.79s	remaining: 566ms
760:	learn: 0.3097161	total: 1.79s	remaining: 564ms
761:	learn: 0.3096898	total: 1.8s	remaining: 561ms
762:	learn: 0.3096462	total: 1.8s	remaining: 559ms
763:	learn: 0.3096245	total: 1.8s	remaining: 556ms
764:	learn: 0.3095021	total: 1.8s	remaining: 554ms
765:	learn: 0.3094463	total: 1.8s	remaining: 552ms
766:	learn: 0.3092539	total: 1.81s	remaining: 549ms
767:	learn: 0.309

924:	learn: 0.2936202	total: 2.21s	remaining: 179ms
925:	learn: 0.2935446	total: 2.21s	remaining: 177ms
926:	learn: 0.2934608	total: 2.21s	remaining: 174ms
927:	learn: 0.2934153	total: 2.22s	remaining: 172ms
928:	learn: 0.2933144	total: 2.22s	remaining: 170ms
929:	learn: 0.2932806	total: 2.22s	remaining: 167ms
930:	learn: 0.2932355	total: 2.23s	remaining: 165ms
931:	learn: 0.2930563	total: 2.23s	remaining: 163ms
932:	learn: 0.2928323	total: 2.23s	remaining: 160ms
933:	learn: 0.2927553	total: 2.23s	remaining: 158ms
934:	learn: 0.2926562	total: 2.24s	remaining: 156ms
935:	learn: 0.2925498	total: 2.24s	remaining: 153ms
936:	learn: 0.2924361	total: 2.24s	remaining: 151ms
937:	learn: 0.2923005	total: 2.25s	remaining: 148ms
938:	learn: 0.2922671	total: 2.25s	remaining: 146ms
939:	learn: 0.2921503	total: 2.25s	remaining: 144ms
940:	learn: 0.2920707	total: 2.25s	remaining: 141ms
941:	learn: 0.2920372	total: 2.26s	remaining: 139ms
942:	learn: 0.2919223	total: 2.26s	remaining: 137ms
943:	learn: 

101:	learn: 0.4536203	total: 231ms	remaining: 2.03s
102:	learn: 0.4526050	total: 234ms	remaining: 2.03s
103:	learn: 0.4516296	total: 236ms	remaining: 2.03s
104:	learn: 0.4506158	total: 238ms	remaining: 2.03s
105:	learn: 0.4497955	total: 240ms	remaining: 2.02s
106:	learn: 0.4486603	total: 242ms	remaining: 2.02s
107:	learn: 0.4477139	total: 245ms	remaining: 2.02s
108:	learn: 0.4469730	total: 247ms	remaining: 2.02s
109:	learn: 0.4459117	total: 250ms	remaining: 2.02s
110:	learn: 0.4447913	total: 253ms	remaining: 2.02s
111:	learn: 0.4440558	total: 255ms	remaining: 2.02s
112:	learn: 0.4430482	total: 257ms	remaining: 2.02s
113:	learn: 0.4421325	total: 259ms	remaining: 2.01s
114:	learn: 0.4416808	total: 261ms	remaining: 2.01s
115:	learn: 0.4408890	total: 263ms	remaining: 2.01s
116:	learn: 0.4400126	total: 267ms	remaining: 2.01s
117:	learn: 0.4389786	total: 269ms	remaining: 2.01s
118:	learn: 0.4383633	total: 271ms	remaining: 2.01s
119:	learn: 0.4378597	total: 274ms	remaining: 2.01s
120:	learn: 

276:	learn: 0.3794953	total: 668ms	remaining: 1.74s
277:	learn: 0.3791046	total: 671ms	remaining: 1.74s
278:	learn: 0.3787562	total: 674ms	remaining: 1.74s
279:	learn: 0.3781945	total: 677ms	remaining: 1.74s
280:	learn: 0.3780106	total: 679ms	remaining: 1.74s
281:	learn: 0.3779124	total: 681ms	remaining: 1.73s
282:	learn: 0.3777313	total: 683ms	remaining: 1.73s
283:	learn: 0.3774729	total: 688ms	remaining: 1.73s
284:	learn: 0.3771795	total: 690ms	remaining: 1.73s
285:	learn: 0.3770477	total: 692ms	remaining: 1.73s
286:	learn: 0.3769122	total: 694ms	remaining: 1.72s
287:	learn: 0.3764001	total: 696ms	remaining: 1.72s
288:	learn: 0.3761206	total: 698ms	remaining: 1.72s
289:	learn: 0.3760491	total: 702ms	remaining: 1.72s
290:	learn: 0.3755514	total: 704ms	remaining: 1.72s
291:	learn: 0.3752151	total: 706ms	remaining: 1.71s
292:	learn: 0.3750460	total: 708ms	remaining: 1.71s
293:	learn: 0.3748820	total: 710ms	remaining: 1.71s
294:	learn: 0.3747639	total: 713ms	remaining: 1.7s
295:	learn: 0

442:	learn: 0.3516073	total: 1.08s	remaining: 1.36s
443:	learn: 0.3513154	total: 1.08s	remaining: 1.36s
444:	learn: 0.3512456	total: 1.08s	remaining: 1.35s
445:	learn: 0.3510523	total: 1.09s	remaining: 1.35s
446:	learn: 0.3509612	total: 1.09s	remaining: 1.35s
447:	learn: 0.3509188	total: 1.09s	remaining: 1.35s
448:	learn: 0.3508937	total: 1.09s	remaining: 1.34s
449:	learn: 0.3508356	total: 1.1s	remaining: 1.34s
450:	learn: 0.3507702	total: 1.1s	remaining: 1.34s
451:	learn: 0.3503908	total: 1.1s	remaining: 1.34s
452:	learn: 0.3503053	total: 1.1s	remaining: 1.33s
453:	learn: 0.3500868	total: 1.11s	remaining: 1.33s
454:	learn: 0.3498251	total: 1.11s	remaining: 1.33s
455:	learn: 0.3497254	total: 1.11s	remaining: 1.33s
456:	learn: 0.3496206	total: 1.11s	remaining: 1.32s
457:	learn: 0.3494930	total: 1.12s	remaining: 1.32s
458:	learn: 0.3493613	total: 1.12s	remaining: 1.32s
459:	learn: 0.3492550	total: 1.12s	remaining: 1.32s
460:	learn: 0.3492484	total: 1.13s	remaining: 1.32s
461:	learn: 0.34

613:	learn: 0.3318350	total: 1.52s	remaining: 954ms
614:	learn: 0.3317966	total: 1.52s	remaining: 952ms
615:	learn: 0.3316493	total: 1.52s	remaining: 949ms
616:	learn: 0.3315595	total: 1.52s	remaining: 946ms
617:	learn: 0.3314929	total: 1.53s	remaining: 944ms
618:	learn: 0.3314066	total: 1.53s	remaining: 943ms
619:	learn: 0.3312806	total: 1.53s	remaining: 940ms
620:	learn: 0.3312167	total: 1.53s	remaining: 937ms
621:	learn: 0.3311830	total: 1.54s	remaining: 935ms
622:	learn: 0.3311595	total: 1.54s	remaining: 932ms
623:	learn: 0.3311094	total: 1.54s	remaining: 931ms
624:	learn: 0.3309404	total: 1.55s	remaining: 928ms
625:	learn: 0.3307459	total: 1.55s	remaining: 926ms
626:	learn: 0.3306110	total: 1.55s	remaining: 923ms
627:	learn: 0.3303238	total: 1.55s	remaining: 920ms
628:	learn: 0.3302273	total: 1.56s	remaining: 918ms
629:	learn: 0.3299449	total: 1.56s	remaining: 916ms
630:	learn: 0.3298333	total: 1.56s	remaining: 914ms
631:	learn: 0.3297462	total: 1.56s	remaining: 912ms
632:	learn: 

775:	learn: 0.3149985	total: 1.97s	remaining: 568ms
776:	learn: 0.3148776	total: 1.97s	remaining: 565ms
777:	learn: 0.3146955	total: 1.97s	remaining: 563ms
778:	learn: 0.3143989	total: 1.97s	remaining: 560ms
779:	learn: 0.3143410	total: 1.98s	remaining: 558ms
780:	learn: 0.3142875	total: 1.98s	remaining: 556ms
781:	learn: 0.3141718	total: 1.98s	remaining: 553ms
782:	learn: 0.3140626	total: 1.99s	remaining: 550ms
783:	learn: 0.3139478	total: 1.99s	remaining: 548ms
784:	learn: 0.3138850	total: 1.99s	remaining: 545ms
785:	learn: 0.3136846	total: 1.99s	remaining: 543ms
786:	learn: 0.3136265	total: 2s	remaining: 541ms
787:	learn: 0.3133252	total: 2s	remaining: 538ms
788:	learn: 0.3132826	total: 2s	remaining: 536ms
789:	learn: 0.3131995	total: 2s	remaining: 533ms
790:	learn: 0.3129380	total: 2.01s	remaining: 530ms
791:	learn: 0.3128585	total: 2.01s	remaining: 528ms
792:	learn: 0.3128099	total: 2.01s	remaining: 526ms
793:	learn: 0.3124371	total: 2.02s	remaining: 523ms
794:	learn: 0.3123482	to

946:	learn: 0.2956307	total: 2.44s	remaining: 136ms
947:	learn: 0.2956137	total: 2.44s	remaining: 134ms
948:	learn: 0.2954247	total: 2.44s	remaining: 131ms
949:	learn: 0.2953604	total: 2.44s	remaining: 129ms
950:	learn: 0.2952570	total: 2.44s	remaining: 126ms
951:	learn: 0.2952167	total: 2.45s	remaining: 123ms
952:	learn: 0.2951578	total: 2.45s	remaining: 121ms
953:	learn: 0.2951092	total: 2.45s	remaining: 118ms
954:	learn: 0.2950035	total: 2.46s	remaining: 116ms
955:	learn: 0.2949005	total: 2.46s	remaining: 113ms
956:	learn: 0.2948098	total: 2.46s	remaining: 111ms
957:	learn: 0.2947320	total: 2.46s	remaining: 108ms
958:	learn: 0.2946253	total: 2.47s	remaining: 105ms
959:	learn: 0.2945657	total: 2.47s	remaining: 103ms
960:	learn: 0.2944985	total: 2.47s	remaining: 100ms
961:	learn: 0.2944349	total: 2.47s	remaining: 97.7ms
962:	learn: 0.2943947	total: 2.48s	remaining: 95.2ms
963:	learn: 0.2942154	total: 2.48s	remaining: 92.6ms
964:	learn: 0.2941846	total: 2.48s	remaining: 90.1ms
965:	lea

122:	learn: 0.4360426	total: 321ms	remaining: 2.29s
123:	learn: 0.4354479	total: 324ms	remaining: 2.29s
124:	learn: 0.4347421	total: 328ms	remaining: 2.3s
125:	learn: 0.4341587	total: 331ms	remaining: 2.29s
126:	learn: 0.4333634	total: 333ms	remaining: 2.29s
127:	learn: 0.4326223	total: 336ms	remaining: 2.29s
128:	learn: 0.4322018	total: 338ms	remaining: 2.28s
129:	learn: 0.4314230	total: 342ms	remaining: 2.29s
130:	learn: 0.4308339	total: 344ms	remaining: 2.28s
131:	learn: 0.4305831	total: 346ms	remaining: 2.27s
132:	learn: 0.4298913	total: 348ms	remaining: 2.27s
133:	learn: 0.4290872	total: 351ms	remaining: 2.27s
134:	learn: 0.4283689	total: 353ms	remaining: 2.26s
135:	learn: 0.4277995	total: 355ms	remaining: 2.26s
136:	learn: 0.4269478	total: 358ms	remaining: 2.25s
137:	learn: 0.4264552	total: 360ms	remaining: 2.25s
138:	learn: 0.4258163	total: 363ms	remaining: 2.25s
139:	learn: 0.4252358	total: 365ms	remaining: 2.24s
140:	learn: 0.4251334	total: 367ms	remaining: 2.24s
141:	learn: 0

293:	learn: 0.3785992	total: 703ms	remaining: 1.69s
294:	learn: 0.3783946	total: 706ms	remaining: 1.69s
295:	learn: 0.3778999	total: 708ms	remaining: 1.68s
296:	learn: 0.3777609	total: 710ms	remaining: 1.68s
297:	learn: 0.3777028	total: 712ms	remaining: 1.68s
298:	learn: 0.3775569	total: 714ms	remaining: 1.68s
299:	learn: 0.3775217	total: 716ms	remaining: 1.67s
300:	learn: 0.3773445	total: 719ms	remaining: 1.67s
301:	learn: 0.3771303	total: 721ms	remaining: 1.67s
302:	learn: 0.3769063	total: 723ms	remaining: 1.66s
303:	learn: 0.3766491	total: 725ms	remaining: 1.66s
304:	learn: 0.3765930	total: 727ms	remaining: 1.66s
305:	learn: 0.3764551	total: 729ms	remaining: 1.65s
306:	learn: 0.3763919	total: 731ms	remaining: 1.65s
307:	learn: 0.3762561	total: 733ms	remaining: 1.65s
308:	learn: 0.3756843	total: 736ms	remaining: 1.64s
309:	learn: 0.3754959	total: 738ms	remaining: 1.64s
310:	learn: 0.3754042	total: 740ms	remaining: 1.64s
311:	learn: 0.3752631	total: 742ms	remaining: 1.64s
312:	learn: 

496:	learn: 0.3483559	total: 1.18s	remaining: 1.19s
497:	learn: 0.3483174	total: 1.18s	remaining: 1.19s
498:	learn: 0.3482743	total: 1.19s	remaining: 1.19s
499:	learn: 0.3481659	total: 1.19s	remaining: 1.19s
500:	learn: 0.3480992	total: 1.2s	remaining: 1.19s
501:	learn: 0.3480131	total: 1.2s	remaining: 1.19s
502:	learn: 0.3478618	total: 1.2s	remaining: 1.19s
503:	learn: 0.3478548	total: 1.21s	remaining: 1.19s
504:	learn: 0.3477347	total: 1.21s	remaining: 1.19s
505:	learn: 0.3476162	total: 1.21s	remaining: 1.18s
506:	learn: 0.3475299	total: 1.22s	remaining: 1.18s
507:	learn: 0.3474611	total: 1.22s	remaining: 1.18s
508:	learn: 0.3472818	total: 1.22s	remaining: 1.18s
509:	learn: 0.3472532	total: 1.22s	remaining: 1.18s
510:	learn: 0.3471482	total: 1.23s	remaining: 1.17s
511:	learn: 0.3470565	total: 1.23s	remaining: 1.17s
512:	learn: 0.3470383	total: 1.23s	remaining: 1.17s
513:	learn: 0.3469840	total: 1.23s	remaining: 1.17s
514:	learn: 0.3469376	total: 1.24s	remaining: 1.16s
515:	learn: 0.3

712:	learn: 0.3261686	total: 1.68s	remaining: 677ms
713:	learn: 0.3258294	total: 1.68s	remaining: 675ms
714:	learn: 0.3257975	total: 1.69s	remaining: 673ms
715:	learn: 0.3257801	total: 1.69s	remaining: 670ms
716:	learn: 0.3257226	total: 1.69s	remaining: 668ms
717:	learn: 0.3255788	total: 1.69s	remaining: 665ms
718:	learn: 0.3255463	total: 1.7s	remaining: 663ms
719:	learn: 0.3254691	total: 1.7s	remaining: 660ms
720:	learn: 0.3254612	total: 1.7s	remaining: 658ms
721:	learn: 0.3254051	total: 1.7s	remaining: 656ms
722:	learn: 0.3253036	total: 1.71s	remaining: 653ms
723:	learn: 0.3251312	total: 1.71s	remaining: 651ms
724:	learn: 0.3251102	total: 1.71s	remaining: 648ms
725:	learn: 0.3250659	total: 1.71s	remaining: 646ms
726:	learn: 0.3250157	total: 1.71s	remaining: 643ms
727:	learn: 0.3249566	total: 1.72s	remaining: 642ms
728:	learn: 0.3248555	total: 1.72s	remaining: 639ms
729:	learn: 0.3246189	total: 1.72s	remaining: 637ms
730:	learn: 0.3244649	total: 1.72s	remaining: 635ms
731:	learn: 0.32

926:	learn: 0.3039024	total: 2.19s	remaining: 173ms
927:	learn: 0.3038256	total: 2.2s	remaining: 170ms
928:	learn: 0.3037401	total: 2.2s	remaining: 168ms
929:	learn: 0.3036186	total: 2.2s	remaining: 166ms
930:	learn: 0.3035423	total: 2.2s	remaining: 163ms
931:	learn: 0.3034760	total: 2.21s	remaining: 161ms
932:	learn: 0.3034075	total: 2.21s	remaining: 159ms
933:	learn: 0.3033312	total: 2.21s	remaining: 156ms
934:	learn: 0.3033025	total: 2.21s	remaining: 154ms
935:	learn: 0.3031769	total: 2.21s	remaining: 151ms
936:	learn: 0.3030932	total: 2.22s	remaining: 149ms
937:	learn: 0.3029012	total: 2.22s	remaining: 147ms
938:	learn: 0.3028381	total: 2.22s	remaining: 144ms
939:	learn: 0.3027825	total: 2.23s	remaining: 142ms
940:	learn: 0.3026274	total: 2.23s	remaining: 140ms
941:	learn: 0.3024469	total: 2.23s	remaining: 137ms
942:	learn: 0.3024099	total: 2.23s	remaining: 135ms
943:	learn: 0.3023066	total: 2.23s	remaining: 133ms
944:	learn: 0.3022172	total: 2.24s	remaining: 130ms
945:	learn: 0.30

151:	learn: 0.4181893	total: 334ms	remaining: 1.86s
152:	learn: 0.4177781	total: 336ms	remaining: 1.86s
153:	learn: 0.4170648	total: 338ms	remaining: 1.86s
154:	learn: 0.4164457	total: 341ms	remaining: 1.86s
155:	learn: 0.4158998	total: 343ms	remaining: 1.85s
156:	learn: 0.4153510	total: 348ms	remaining: 1.87s
157:	learn: 0.4151467	total: 350ms	remaining: 1.86s
158:	learn: 0.4149021	total: 351ms	remaining: 1.86s
159:	learn: 0.4143001	total: 353ms	remaining: 1.85s
160:	learn: 0.4137956	total: 356ms	remaining: 1.85s
161:	learn: 0.4135247	total: 358ms	remaining: 1.85s
162:	learn: 0.4130896	total: 362ms	remaining: 1.86s
163:	learn: 0.4127945	total: 364ms	remaining: 1.86s
164:	learn: 0.4122556	total: 367ms	remaining: 1.86s
165:	learn: 0.4121276	total: 368ms	remaining: 1.85s
166:	learn: 0.4116069	total: 370ms	remaining: 1.85s
167:	learn: 0.4112351	total: 373ms	remaining: 1.84s
168:	learn: 0.4105124	total: 377ms	remaining: 1.85s
169:	learn: 0.4103214	total: 379ms	remaining: 1.85s
170:	learn: 

380:	learn: 0.3583006	total: 842ms	remaining: 1.37s
381:	learn: 0.3581945	total: 845ms	remaining: 1.37s
382:	learn: 0.3581444	total: 847ms	remaining: 1.36s
383:	learn: 0.3579456	total: 849ms	remaining: 1.36s
384:	learn: 0.3577644	total: 851ms	remaining: 1.36s
385:	learn: 0.3573964	total: 853ms	remaining: 1.36s
386:	learn: 0.3572341	total: 856ms	remaining: 1.35s
387:	learn: 0.3571075	total: 859ms	remaining: 1.35s
388:	learn: 0.3570415	total: 861ms	remaining: 1.35s
389:	learn: 0.3570162	total: 863ms	remaining: 1.35s
390:	learn: 0.3568939	total: 866ms	remaining: 1.35s
391:	learn: 0.3567544	total: 868ms	remaining: 1.35s
392:	learn: 0.3566298	total: 870ms	remaining: 1.34s
393:	learn: 0.3565268	total: 872ms	remaining: 1.34s
394:	learn: 0.3562932	total: 874ms	remaining: 1.34s
395:	learn: 0.3561820	total: 877ms	remaining: 1.34s
396:	learn: 0.3560488	total: 879ms	remaining: 1.33s
397:	learn: 0.3556823	total: 881ms	remaining: 1.33s
398:	learn: 0.3556096	total: 883ms	remaining: 1.33s
399:	learn: 

543:	learn: 0.3359369	total: 1.2s	remaining: 1.01s
544:	learn: 0.3358906	total: 1.2s	remaining: 1s
545:	learn: 0.3357956	total: 1.21s	remaining: 1s
546:	learn: 0.3356929	total: 1.21s	remaining: 1s
547:	learn: 0.3354949	total: 1.21s	remaining: 998ms
548:	learn: 0.3354250	total: 1.21s	remaining: 996ms
549:	learn: 0.3354044	total: 1.21s	remaining: 994ms
550:	learn: 0.3353450	total: 1.22s	remaining: 991ms
551:	learn: 0.3352363	total: 1.22s	remaining: 989ms
552:	learn: 0.3351551	total: 1.22s	remaining: 987ms
553:	learn: 0.3350463	total: 1.22s	remaining: 985ms
554:	learn: 0.3350410	total: 1.23s	remaining: 982ms
555:	learn: 0.3349380	total: 1.23s	remaining: 980ms
556:	learn: 0.3349122	total: 1.23s	remaining: 978ms
557:	learn: 0.3348690	total: 1.23s	remaining: 976ms
558:	learn: 0.3347214	total: 1.23s	remaining: 974ms
559:	learn: 0.3346901	total: 1.24s	remaining: 971ms
560:	learn: 0.3345872	total: 1.24s	remaining: 969ms
561:	learn: 0.3345269	total: 1.24s	remaining: 967ms
562:	learn: 0.3344923	t

771:	learn: 0.3097235	total: 1.7s	remaining: 502ms
772:	learn: 0.3096480	total: 1.7s	remaining: 500ms
773:	learn: 0.3096138	total: 1.7s	remaining: 498ms
774:	learn: 0.3095166	total: 1.71s	remaining: 495ms
775:	learn: 0.3093849	total: 1.71s	remaining: 493ms
776:	learn: 0.3090309	total: 1.71s	remaining: 491ms
777:	learn: 0.3089629	total: 1.71s	remaining: 489ms
778:	learn: 0.3088855	total: 1.72s	remaining: 487ms
779:	learn: 0.3087741	total: 1.72s	remaining: 485ms
780:	learn: 0.3087209	total: 1.72s	remaining: 482ms
781:	learn: 0.3086146	total: 1.72s	remaining: 480ms
782:	learn: 0.3084868	total: 1.72s	remaining: 478ms
783:	learn: 0.3084453	total: 1.73s	remaining: 476ms
784:	learn: 0.3083822	total: 1.73s	remaining: 474ms
785:	learn: 0.3082427	total: 1.73s	remaining: 472ms
786:	learn: 0.3081656	total: 1.73s	remaining: 469ms
787:	learn: 0.3080661	total: 1.74s	remaining: 467ms
788:	learn: 0.3079877	total: 1.74s	remaining: 465ms
789:	learn: 0.3077805	total: 1.74s	remaining: 463ms
790:	learn: 0.3

998:	learn: 0.2852290	total: 2.21s	remaining: 2.22ms
999:	learn: 0.2849626	total: 2.22s	remaining: 0us
Learning rate set to 0.00852
0:	learn: 0.6880202	total: 9.82ms	remaining: 9.81s
1:	learn: 0.6825157	total: 15.9ms	remaining: 7.91s
2:	learn: 0.6778669	total: 20.5ms	remaining: 6.81s
3:	learn: 0.6730467	total: 23.4ms	remaining: 5.82s
4:	learn: 0.6688308	total: 26.1ms	remaining: 5.2s
5:	learn: 0.6645416	total: 29.7ms	remaining: 4.91s
6:	learn: 0.6616584	total: 31.9ms	remaining: 4.52s
7:	learn: 0.6569178	total: 34.9ms	remaining: 4.33s
8:	learn: 0.6525867	total: 37.6ms	remaining: 4.14s
9:	learn: 0.6485595	total: 39.6ms	remaining: 3.92s
10:	learn: 0.6438113	total: 42.1ms	remaining: 3.79s
11:	learn: 0.6394060	total: 44.5ms	remaining: 3.67s
12:	learn: 0.6355295	total: 47ms	remaining: 3.57s
13:	learn: 0.6322670	total: 49.3ms	remaining: 3.47s
14:	learn: 0.6276680	total: 51.4ms	remaining: 3.38s
15:	learn: 0.6237059	total: 53.7ms	remaining: 3.3s
16:	learn: 0.6202299	total: 55.9ms	remaining: 3.23

184:	learn: 0.4030126	total: 434ms	remaining: 1.91s
185:	learn: 0.4026394	total: 436ms	remaining: 1.91s
186:	learn: 0.4022165	total: 439ms	remaining: 1.91s
187:	learn: 0.4019073	total: 441ms	remaining: 1.9s
188:	learn: 0.4013350	total: 444ms	remaining: 1.9s
189:	learn: 0.4009886	total: 446ms	remaining: 1.9s
190:	learn: 0.4006535	total: 448ms	remaining: 1.9s
191:	learn: 0.4002509	total: 451ms	remaining: 1.9s
192:	learn: 0.3999927	total: 454ms	remaining: 1.9s
193:	learn: 0.3996174	total: 456ms	remaining: 1.9s
194:	learn: 0.3991735	total: 459ms	remaining: 1.89s
195:	learn: 0.3986708	total: 461ms	remaining: 1.89s
196:	learn: 0.3981693	total: 463ms	remaining: 1.89s
197:	learn: 0.3976570	total: 466ms	remaining: 1.89s
198:	learn: 0.3975584	total: 468ms	remaining: 1.88s
199:	learn: 0.3971865	total: 470ms	remaining: 1.88s
200:	learn: 0.3969872	total: 472ms	remaining: 1.88s
201:	learn: 0.3967564	total: 474ms	remaining: 1.87s
202:	learn: 0.3966656	total: 476ms	remaining: 1.87s
203:	learn: 0.39637

345:	learn: 0.3667457	total: 844ms	remaining: 1.59s
346:	learn: 0.3666561	total: 847ms	remaining: 1.59s
347:	learn: 0.3665385	total: 849ms	remaining: 1.59s
348:	learn: 0.3664232	total: 852ms	remaining: 1.59s
349:	learn: 0.3662276	total: 854ms	remaining: 1.59s
350:	learn: 0.3661036	total: 857ms	remaining: 1.58s
351:	learn: 0.3660206	total: 859ms	remaining: 1.58s
352:	learn: 0.3659383	total: 862ms	remaining: 1.58s
353:	learn: 0.3659291	total: 863ms	remaining: 1.57s
354:	learn: 0.3658525	total: 866ms	remaining: 1.57s
355:	learn: 0.3657968	total: 868ms	remaining: 1.57s
356:	learn: 0.3656568	total: 871ms	remaining: 1.57s
357:	learn: 0.3655794	total: 873ms	remaining: 1.56s
358:	learn: 0.3652722	total: 875ms	remaining: 1.56s
359:	learn: 0.3651247	total: 878ms	remaining: 1.56s
360:	learn: 0.3649972	total: 881ms	remaining: 1.56s
361:	learn: 0.3647881	total: 883ms	remaining: 1.56s
362:	learn: 0.3646192	total: 886ms	remaining: 1.55s
363:	learn: 0.3644034	total: 888ms	remaining: 1.55s
364:	learn: 

516:	learn: 0.3446230	total: 1.28s	remaining: 1.2s
517:	learn: 0.3445396	total: 1.28s	remaining: 1.19s
518:	learn: 0.3444682	total: 1.28s	remaining: 1.19s
519:	learn: 0.3444290	total: 1.29s	remaining: 1.19s
520:	learn: 0.3444236	total: 1.29s	remaining: 1.19s
521:	learn: 0.3443476	total: 1.29s	remaining: 1.18s
522:	learn: 0.3442922	total: 1.29s	remaining: 1.18s
523:	learn: 0.3441812	total: 1.3s	remaining: 1.18s
524:	learn: 0.3439696	total: 1.3s	remaining: 1.18s
525:	learn: 0.3438366	total: 1.3s	remaining: 1.17s
526:	learn: 0.3437840	total: 1.31s	remaining: 1.17s
527:	learn: 0.3437142	total: 1.31s	remaining: 1.17s
528:	learn: 0.3436561	total: 1.31s	remaining: 1.17s
529:	learn: 0.3435182	total: 1.31s	remaining: 1.17s
530:	learn: 0.3434289	total: 1.32s	remaining: 1.16s
531:	learn: 0.3433680	total: 1.32s	remaining: 1.16s
532:	learn: 0.3430867	total: 1.32s	remaining: 1.16s
533:	learn: 0.3430339	total: 1.32s	remaining: 1.16s
534:	learn: 0.3427987	total: 1.33s	remaining: 1.15s
535:	learn: 0.34

704:	learn: 0.3259922	total: 1.77s	remaining: 743ms
705:	learn: 0.3259673	total: 1.78s	remaining: 740ms
706:	learn: 0.3258868	total: 1.78s	remaining: 738ms
707:	learn: 0.3257821	total: 1.78s	remaining: 735ms
708:	learn: 0.3255349	total: 1.79s	remaining: 733ms
709:	learn: 0.3254826	total: 1.79s	remaining: 731ms
710:	learn: 0.3253833	total: 1.79s	remaining: 729ms
711:	learn: 0.3253142	total: 1.79s	remaining: 726ms
712:	learn: 0.3250921	total: 1.8s	remaining: 724ms
713:	learn: 0.3250101	total: 1.8s	remaining: 722ms
714:	learn: 0.3249524	total: 1.8s	remaining: 720ms
715:	learn: 0.3248274	total: 1.81s	remaining: 717ms
716:	learn: 0.3247347	total: 1.81s	remaining: 715ms
717:	learn: 0.3246099	total: 1.81s	remaining: 712ms
718:	learn: 0.3245211	total: 1.82s	remaining: 710ms
719:	learn: 0.3243772	total: 1.82s	remaining: 708ms
720:	learn: 0.3243252	total: 1.82s	remaining: 705ms
721:	learn: 0.3242214	total: 1.82s	remaining: 703ms
722:	learn: 0.3241152	total: 1.83s	remaining: 700ms
723:	learn: 0.3

894:	learn: 0.3063674	total: 2.28s	remaining: 267ms
895:	learn: 0.3063594	total: 2.28s	remaining: 264ms
896:	learn: 0.3060965	total: 2.28s	remaining: 262ms
897:	learn: 0.3059821	total: 2.28s	remaining: 259ms
898:	learn: 0.3059075	total: 2.29s	remaining: 257ms
899:	learn: 0.3058083	total: 2.29s	remaining: 254ms
900:	learn: 0.3056933	total: 2.29s	remaining: 252ms
901:	learn: 0.3056392	total: 2.29s	remaining: 249ms
902:	learn: 0.3054777	total: 2.3s	remaining: 247ms
903:	learn: 0.3052011	total: 2.3s	remaining: 244ms
904:	learn: 0.3051053	total: 2.3s	remaining: 242ms
905:	learn: 0.3050553	total: 2.31s	remaining: 239ms
906:	learn: 0.3049907	total: 2.31s	remaining: 237ms
907:	learn: 0.3048715	total: 2.31s	remaining: 234ms
908:	learn: 0.3048130	total: 2.31s	remaining: 232ms
909:	learn: 0.3045232	total: 2.32s	remaining: 229ms
910:	learn: 0.3043391	total: 2.32s	remaining: 227ms
911:	learn: 0.3043040	total: 2.32s	remaining: 224ms
912:	learn: 0.3042580	total: 2.33s	remaining: 222ms
913:	learn: 0.3

77:	learn: 0.4657171	total: 169ms	remaining: 2s
78:	learn: 0.4642137	total: 172ms	remaining: 2s
79:	learn: 0.4627392	total: 174ms	remaining: 2s
80:	learn: 0.4613354	total: 176ms	remaining: 2s
81:	learn: 0.4599993	total: 179ms	remaining: 2s
82:	learn: 0.4587577	total: 181ms	remaining: 2s
83:	learn: 0.4576799	total: 184ms	remaining: 2s
84:	learn: 0.4569939	total: 186ms	remaining: 2s
85:	learn: 0.4557584	total: 188ms	remaining: 2s
86:	learn: 0.4548694	total: 191ms	remaining: 2s
87:	learn: 0.4534937	total: 193ms	remaining: 2s
88:	learn: 0.4523146	total: 195ms	remaining: 2s
89:	learn: 0.4511293	total: 198ms	remaining: 2s
90:	learn: 0.4501448	total: 199ms	remaining: 1.99s
91:	learn: 0.4491348	total: 202ms	remaining: 1.99s
92:	learn: 0.4474246	total: 204ms	remaining: 1.99s
93:	learn: 0.4468434	total: 205ms	remaining: 1.98s
94:	learn: 0.4458264	total: 207ms	remaining: 1.98s
95:	learn: 0.4449749	total: 209ms	remaining: 1.97s
96:	learn: 0.4445482	total: 211ms	remaining: 1.96s
97:	learn: 0.443382

241:	learn: 0.3726096	total: 558ms	remaining: 1.75s
242:	learn: 0.3725940	total: 560ms	remaining: 1.74s
243:	learn: 0.3721088	total: 562ms	remaining: 1.74s
244:	learn: 0.3718946	total: 564ms	remaining: 1.74s
245:	learn: 0.3717262	total: 567ms	remaining: 1.74s
246:	learn: 0.3715832	total: 569ms	remaining: 1.74s
247:	learn: 0.3713728	total: 572ms	remaining: 1.73s
248:	learn: 0.3709674	total: 574ms	remaining: 1.73s
249:	learn: 0.3708843	total: 576ms	remaining: 1.73s
250:	learn: 0.3706977	total: 578ms	remaining: 1.73s
251:	learn: 0.3705788	total: 582ms	remaining: 1.73s
252:	learn: 0.3702997	total: 584ms	remaining: 1.72s
253:	learn: 0.3701316	total: 587ms	remaining: 1.72s
254:	learn: 0.3699051	total: 589ms	remaining: 1.72s
255:	learn: 0.3698147	total: 591ms	remaining: 1.72s
256:	learn: 0.3697678	total: 593ms	remaining: 1.72s
257:	learn: 0.3695893	total: 596ms	remaining: 1.71s
258:	learn: 0.3694061	total: 598ms	remaining: 1.71s
259:	learn: 0.3693209	total: 601ms	remaining: 1.71s
260:	learn: 

416:	learn: 0.3434447	total: 1.01s	remaining: 1.41s
417:	learn: 0.3433907	total: 1.01s	remaining: 1.41s
418:	learn: 0.3432659	total: 1.01s	remaining: 1.41s
419:	learn: 0.3432605	total: 1.01s	remaining: 1.4s
420:	learn: 0.3431607	total: 1.02s	remaining: 1.4s
421:	learn: 0.3430215	total: 1.02s	remaining: 1.4s
422:	learn: 0.3429511	total: 1.02s	remaining: 1.39s
423:	learn: 0.3428608	total: 1.02s	remaining: 1.39s
424:	learn: 0.3427559	total: 1.03s	remaining: 1.39s
425:	learn: 0.3426658	total: 1.03s	remaining: 1.39s
426:	learn: 0.3425965	total: 1.03s	remaining: 1.39s
427:	learn: 0.3425565	total: 1.03s	remaining: 1.38s
428:	learn: 0.3425104	total: 1.04s	remaining: 1.38s
429:	learn: 0.3421810	total: 1.04s	remaining: 1.38s
430:	learn: 0.3421327	total: 1.04s	remaining: 1.38s
431:	learn: 0.3419036	total: 1.04s	remaining: 1.37s
432:	learn: 0.3416681	total: 1.05s	remaining: 1.37s
433:	learn: 0.3415455	total: 1.05s	remaining: 1.37s
434:	learn: 0.3414570	total: 1.05s	remaining: 1.37s
435:	learn: 0.3

616:	learn: 0.3208493	total: 1.52s	remaining: 942ms
617:	learn: 0.3208078	total: 1.52s	remaining: 939ms
618:	learn: 0.3206683	total: 1.52s	remaining: 937ms
619:	learn: 0.3205194	total: 1.52s	remaining: 934ms
620:	learn: 0.3203977	total: 1.53s	remaining: 931ms
621:	learn: 0.3203698	total: 1.53s	remaining: 929ms
622:	learn: 0.3201751	total: 1.53s	remaining: 926ms
623:	learn: 0.3201100	total: 1.53s	remaining: 924ms
624:	learn: 0.3200427	total: 1.53s	remaining: 921ms
625:	learn: 0.3199601	total: 1.54s	remaining: 920ms
626:	learn: 0.3198319	total: 1.54s	remaining: 918ms
627:	learn: 0.3196437	total: 1.54s	remaining: 915ms
628:	learn: 0.3195867	total: 1.55s	remaining: 913ms
629:	learn: 0.3194881	total: 1.55s	remaining: 910ms
630:	learn: 0.3193993	total: 1.55s	remaining: 908ms
631:	learn: 0.3193733	total: 1.55s	remaining: 905ms
632:	learn: 0.3192480	total: 1.56s	remaining: 903ms
633:	learn: 0.3189493	total: 1.56s	remaining: 900ms
634:	learn: 0.3188970	total: 1.56s	remaining: 897ms
635:	learn: 

776:	learn: 0.3032605	total: 1.89s	remaining: 543ms
777:	learn: 0.3030896	total: 1.9s	remaining: 541ms
778:	learn: 0.3030065	total: 1.9s	remaining: 538ms
779:	learn: 0.3028997	total: 1.9s	remaining: 536ms
780:	learn: 0.3028485	total: 1.9s	remaining: 533ms
781:	learn: 0.3027826	total: 1.9s	remaining: 531ms
782:	learn: 0.3026828	total: 1.91s	remaining: 529ms
783:	learn: 0.3025816	total: 1.91s	remaining: 526ms
784:	learn: 0.3025368	total: 1.91s	remaining: 524ms
785:	learn: 0.3024857	total: 1.91s	remaining: 521ms
786:	learn: 0.3024066	total: 1.92s	remaining: 519ms
787:	learn: 0.3023781	total: 1.92s	remaining: 516ms
788:	learn: 0.3022462	total: 1.92s	remaining: 514ms
789:	learn: 0.3021055	total: 1.92s	remaining: 511ms
790:	learn: 0.3020773	total: 1.93s	remaining: 509ms
791:	learn: 0.3019980	total: 1.93s	remaining: 506ms
792:	learn: 0.3019111	total: 1.93s	remaining: 504ms
793:	learn: 0.3018338	total: 1.93s	remaining: 502ms
794:	learn: 0.3017247	total: 1.94s	remaining: 499ms
795:	learn: 0.301

960:	learn: 0.2846708	total: 2.35s	remaining: 95.4ms
961:	learn: 0.2846051	total: 2.35s	remaining: 92.9ms
962:	learn: 0.2845835	total: 2.35s	remaining: 90.5ms
963:	learn: 0.2845488	total: 2.36s	remaining: 88ms
964:	learn: 0.2844751	total: 2.36s	remaining: 85.6ms
965:	learn: 0.2844506	total: 2.36s	remaining: 83.1ms
966:	learn: 0.2843458	total: 2.36s	remaining: 80.7ms
967:	learn: 0.2843210	total: 2.37s	remaining: 78.2ms
968:	learn: 0.2842908	total: 2.37s	remaining: 75.8ms
969:	learn: 0.2842605	total: 2.37s	remaining: 73.3ms
970:	learn: 0.2841591	total: 2.37s	remaining: 70.9ms
971:	learn: 0.2839612	total: 2.38s	remaining: 68.4ms
972:	learn: 0.2838431	total: 2.38s	remaining: 66ms
973:	learn: 0.2838001	total: 2.38s	remaining: 63.5ms
974:	learn: 0.2836318	total: 2.38s	remaining: 61.1ms
975:	learn: 0.2835952	total: 2.38s	remaining: 58.6ms
976:	learn: 0.2834434	total: 2.39s	remaining: 56.2ms
977:	learn: 0.2832468	total: 2.39s	remaining: 53.7ms
978:	learn: 0.2832169	total: 2.39s	remaining: 51.3

148:	learn: 0.4170011	total: 330ms	remaining: 1.88s
149:	learn: 0.4164542	total: 332ms	remaining: 1.88s
150:	learn: 0.4160847	total: 334ms	remaining: 1.88s
151:	learn: 0.4157401	total: 337ms	remaining: 1.88s
152:	learn: 0.4151799	total: 339ms	remaining: 1.88s
153:	learn: 0.4148651	total: 341ms	remaining: 1.87s
154:	learn: 0.4144109	total: 345ms	remaining: 1.88s
155:	learn: 0.4140707	total: 347ms	remaining: 1.88s
156:	learn: 0.4136287	total: 349ms	remaining: 1.88s
157:	learn: 0.4132275	total: 352ms	remaining: 1.87s
158:	learn: 0.4125985	total: 354ms	remaining: 1.87s
159:	learn: 0.4121901	total: 356ms	remaining: 1.87s
160:	learn: 0.4117703	total: 359ms	remaining: 1.87s
161:	learn: 0.4114749	total: 361ms	remaining: 1.87s
162:	learn: 0.4111015	total: 364ms	remaining: 1.87s
163:	learn: 0.4106619	total: 366ms	remaining: 1.87s
164:	learn: 0.4102233	total: 368ms	remaining: 1.86s
165:	learn: 0.4097338	total: 371ms	remaining: 1.86s
166:	learn: 0.4094260	total: 374ms	remaining: 1.86s
167:	learn: 

373:	learn: 0.3594154	total: 842ms	remaining: 1.41s
374:	learn: 0.3593718	total: 844ms	remaining: 1.41s
375:	learn: 0.3591882	total: 846ms	remaining: 1.4s
376:	learn: 0.3591269	total: 848ms	remaining: 1.4s
377:	learn: 0.3590365	total: 850ms	remaining: 1.4s
378:	learn: 0.3590300	total: 852ms	remaining: 1.4s
379:	learn: 0.3589157	total: 855ms	remaining: 1.39s
380:	learn: 0.3587698	total: 858ms	remaining: 1.39s
381:	learn: 0.3585304	total: 860ms	remaining: 1.39s
382:	learn: 0.3584342	total: 863ms	remaining: 1.39s
383:	learn: 0.3581097	total: 865ms	remaining: 1.39s
384:	learn: 0.3579616	total: 867ms	remaining: 1.38s
385:	learn: 0.3579036	total: 869ms	remaining: 1.38s
386:	learn: 0.3578218	total: 871ms	remaining: 1.38s
387:	learn: 0.3576614	total: 874ms	remaining: 1.38s
388:	learn: 0.3575422	total: 876ms	remaining: 1.38s
389:	learn: 0.3573256	total: 879ms	remaining: 1.37s
390:	learn: 0.3573174	total: 880ms	remaining: 1.37s
391:	learn: 0.3572374	total: 882ms	remaining: 1.37s
392:	learn: 0.35

535:	learn: 0.3391947	total: 1.2s	remaining: 1.04s
536:	learn: 0.3391047	total: 1.2s	remaining: 1.03s
537:	learn: 0.3388072	total: 1.2s	remaining: 1.03s
538:	learn: 0.3387498	total: 1.2s	remaining: 1.03s
539:	learn: 0.3386588	total: 1.21s	remaining: 1.03s
540:	learn: 0.3384193	total: 1.21s	remaining: 1.03s
541:	learn: 0.3382922	total: 1.21s	remaining: 1.02s
542:	learn: 0.3381902	total: 1.21s	remaining: 1.02s
543:	learn: 0.3380644	total: 1.22s	remaining: 1.02s
544:	learn: 0.3379169	total: 1.22s	remaining: 1.02s
545:	learn: 0.3378061	total: 1.22s	remaining: 1.01s
546:	learn: 0.3377667	total: 1.22s	remaining: 1.01s
547:	learn: 0.3377168	total: 1.23s	remaining: 1.01s
548:	learn: 0.3375853	total: 1.23s	remaining: 1.01s
549:	learn: 0.3374393	total: 1.23s	remaining: 1.01s
550:	learn: 0.3374329	total: 1.23s	remaining: 1s
551:	learn: 0.3373915	total: 1.23s	remaining: 1s
552:	learn: 0.3372713	total: 1.24s	remaining: 999ms
553:	learn: 0.3369384	total: 1.24s	remaining: 997ms
554:	learn: 0.3368270	

741:	learn: 0.3160138	total: 1.68s	remaining: 584ms
742:	learn: 0.3159452	total: 1.68s	remaining: 582ms
743:	learn: 0.3157773	total: 1.69s	remaining: 580ms
744:	learn: 0.3156901	total: 1.69s	remaining: 578ms
745:	learn: 0.3155482	total: 1.69s	remaining: 575ms
746:	learn: 0.3154822	total: 1.69s	remaining: 573ms
747:	learn: 0.3153869	total: 1.7s	remaining: 571ms
748:	learn: 0.3152932	total: 1.7s	remaining: 569ms
749:	learn: 0.3151580	total: 1.7s	remaining: 567ms
750:	learn: 0.3151043	total: 1.7s	remaining: 564ms
751:	learn: 0.3148760	total: 1.7s	remaining: 562ms
752:	learn: 0.3147378	total: 1.71s	remaining: 560ms
753:	learn: 0.3145527	total: 1.71s	remaining: 558ms
754:	learn: 0.3144760	total: 1.71s	remaining: 555ms
755:	learn: 0.3143279	total: 1.71s	remaining: 553ms
756:	learn: 0.3142710	total: 1.72s	remaining: 551ms
757:	learn: 0.3142119	total: 1.72s	remaining: 549ms
758:	learn: 0.3141607	total: 1.72s	remaining: 546ms
759:	learn: 0.3139963	total: 1.72s	remaining: 544ms
760:	learn: 0.313

970:	learn: 0.2908599	total: 2.2s	remaining: 65.6ms
971:	learn: 0.2907265	total: 2.2s	remaining: 63.4ms
972:	learn: 0.2906311	total: 2.2s	remaining: 61.1ms
973:	learn: 0.2906073	total: 2.2s	remaining: 58.8ms
974:	learn: 0.2904372	total: 2.21s	remaining: 56.6ms
975:	learn: 0.2903731	total: 2.21s	remaining: 54.3ms
976:	learn: 0.2903040	total: 2.21s	remaining: 52.1ms
977:	learn: 0.2902568	total: 2.21s	remaining: 49.8ms
978:	learn: 0.2901955	total: 2.22s	remaining: 47.6ms
979:	learn: 0.2900554	total: 2.22s	remaining: 45.3ms
980:	learn: 0.2898601	total: 2.22s	remaining: 43ms
981:	learn: 0.2897642	total: 2.22s	remaining: 40.8ms
982:	learn: 0.2897117	total: 2.23s	remaining: 38.5ms
983:	learn: 0.2895685	total: 2.23s	remaining: 36.2ms
984:	learn: 0.2894287	total: 2.23s	remaining: 34ms
985:	learn: 0.2893247	total: 2.23s	remaining: 31.7ms
986:	learn: 0.2891162	total: 2.23s	remaining: 29.4ms
987:	learn: 0.2889999	total: 2.24s	remaining: 27.2ms
988:	learn: 0.2889028	total: 2.24s	remaining: 24.9ms
9

145:	learn: 0.4236534	total: 340ms	remaining: 1.99s
146:	learn: 0.4232307	total: 342ms	remaining: 1.99s
147:	learn: 0.4231004	total: 344ms	remaining: 1.98s
148:	learn: 0.4225931	total: 346ms	remaining: 1.98s
149:	learn: 0.4219922	total: 348ms	remaining: 1.97s
150:	learn: 0.4214148	total: 351ms	remaining: 1.97s
151:	learn: 0.4210217	total: 353ms	remaining: 1.97s
152:	learn: 0.4205190	total: 356ms	remaining: 1.97s
153:	learn: 0.4203292	total: 357ms	remaining: 1.96s
154:	learn: 0.4196348	total: 360ms	remaining: 1.96s
155:	learn: 0.4192977	total: 362ms	remaining: 1.96s
156:	learn: 0.4188608	total: 364ms	remaining: 1.96s
157:	learn: 0.4182199	total: 366ms	remaining: 1.95s
158:	learn: 0.4176683	total: 369ms	remaining: 1.95s
159:	learn: 0.4172790	total: 371ms	remaining: 1.95s
160:	learn: 0.4169319	total: 373ms	remaining: 1.94s
161:	learn: 0.4164689	total: 375ms	remaining: 1.94s
162:	learn: 0.4159431	total: 378ms	remaining: 1.94s
163:	learn: 0.4158237	total: 379ms	remaining: 1.93s
164:	learn: 

303:	learn: 0.3762653	total: 684ms	remaining: 1.57s
304:	learn: 0.3760454	total: 687ms	remaining: 1.56s
305:	learn: 0.3758948	total: 689ms	remaining: 1.56s
306:	learn: 0.3758032	total: 691ms	remaining: 1.56s
307:	learn: 0.3755585	total: 694ms	remaining: 1.56s
308:	learn: 0.3754771	total: 697ms	remaining: 1.56s
309:	learn: 0.3752490	total: 699ms	remaining: 1.56s
310:	learn: 0.3751252	total: 701ms	remaining: 1.55s
311:	learn: 0.3749765	total: 703ms	remaining: 1.55s
312:	learn: 0.3749052	total: 706ms	remaining: 1.55s
313:	learn: 0.3748372	total: 708ms	remaining: 1.55s
314:	learn: 0.3745782	total: 711ms	remaining: 1.54s
315:	learn: 0.3744178	total: 713ms	remaining: 1.54s
316:	learn: 0.3742025	total: 715ms	remaining: 1.54s
317:	learn: 0.3740923	total: 717ms	remaining: 1.54s
318:	learn: 0.3738273	total: 719ms	remaining: 1.53s
319:	learn: 0.3736704	total: 722ms	remaining: 1.53s
320:	learn: 0.3735639	total: 724ms	remaining: 1.53s
321:	learn: 0.3733628	total: 726ms	remaining: 1.53s
322:	learn: 

526:	learn: 0.3472789	total: 1.2s	remaining: 1.08s
527:	learn: 0.3472035	total: 1.2s	remaining: 1.07s
528:	learn: 0.3469998	total: 1.2s	remaining: 1.07s
529:	learn: 0.3469569	total: 1.21s	remaining: 1.07s
530:	learn: 0.3467906	total: 1.21s	remaining: 1.07s
531:	learn: 0.3465994	total: 1.21s	remaining: 1.06s
532:	learn: 0.3465397	total: 1.22s	remaining: 1.06s
533:	learn: 0.3464535	total: 1.22s	remaining: 1.06s
534:	learn: 0.3464487	total: 1.22s	remaining: 1.06s
535:	learn: 0.3464181	total: 1.22s	remaining: 1.06s
536:	learn: 0.3463715	total: 1.22s	remaining: 1.05s
537:	learn: 0.3463049	total: 1.23s	remaining: 1.05s
538:	learn: 0.3462696	total: 1.23s	remaining: 1.05s
539:	learn: 0.3461791	total: 1.23s	remaining: 1.05s
540:	learn: 0.3461043	total: 1.24s	remaining: 1.05s
541:	learn: 0.3460134	total: 1.24s	remaining: 1.04s
542:	learn: 0.3458821	total: 1.24s	remaining: 1.04s
543:	learn: 0.3457748	total: 1.24s	remaining: 1.04s
544:	learn: 0.3455724	total: 1.25s	remaining: 1.04s
545:	learn: 0.3

747:	learn: 0.3242361	total: 1.71s	remaining: 576ms
748:	learn: 0.3241012	total: 1.71s	remaining: 574ms
749:	learn: 0.3239494	total: 1.72s	remaining: 572ms
750:	learn: 0.3237631	total: 1.72s	remaining: 570ms
751:	learn: 0.3236840	total: 1.72s	remaining: 567ms
752:	learn: 0.3233944	total: 1.72s	remaining: 565ms
753:	learn: 0.3233568	total: 1.72s	remaining: 563ms
754:	learn: 0.3232779	total: 1.73s	remaining: 560ms
755:	learn: 0.3230228	total: 1.73s	remaining: 558ms
756:	learn: 0.3229588	total: 1.73s	remaining: 556ms
757:	learn: 0.3227976	total: 1.73s	remaining: 554ms
758:	learn: 0.3227304	total: 1.74s	remaining: 551ms
759:	learn: 0.3226511	total: 1.74s	remaining: 549ms
760:	learn: 0.3225419	total: 1.74s	remaining: 547ms
761:	learn: 0.3224751	total: 1.74s	remaining: 544ms
762:	learn: 0.3224015	total: 1.75s	remaining: 542ms
763:	learn: 0.3222361	total: 1.75s	remaining: 540ms
764:	learn: 0.3217323	total: 1.75s	remaining: 538ms
765:	learn: 0.3216326	total: 1.75s	remaining: 536ms
766:	learn: 

963:	learn: 0.2998610	total: 2.23s	remaining: 83.2ms
964:	learn: 0.2997637	total: 2.23s	remaining: 80.9ms
965:	learn: 0.2996954	total: 2.23s	remaining: 78.5ms
966:	learn: 0.2994990	total: 2.23s	remaining: 76.2ms
967:	learn: 0.2993436	total: 2.24s	remaining: 73.9ms
968:	learn: 0.2992701	total: 2.24s	remaining: 71.6ms
969:	learn: 0.2991630	total: 2.24s	remaining: 69.3ms
970:	learn: 0.2990324	total: 2.24s	remaining: 67ms
971:	learn: 0.2987403	total: 2.25s	remaining: 64.7ms
972:	learn: 0.2986235	total: 2.25s	remaining: 62.4ms
973:	learn: 0.2985712	total: 2.25s	remaining: 60.1ms
974:	learn: 0.2982738	total: 2.25s	remaining: 57.8ms
975:	learn: 0.2981602	total: 2.26s	remaining: 55.5ms
976:	learn: 0.2981263	total: 2.26s	remaining: 53.2ms
977:	learn: 0.2980992	total: 2.26s	remaining: 50.9ms
978:	learn: 0.2978396	total: 2.26s	remaining: 48.5ms
979:	learn: 0.2977028	total: 2.27s	remaining: 46.2ms
980:	learn: 0.2976436	total: 2.27s	remaining: 43.9ms
981:	learn: 0.2974822	total: 2.27s	remaining: 41

126:	learn: 0.4287214	total: 358ms	remaining: 2.46s
127:	learn: 0.4279456	total: 361ms	remaining: 2.46s
128:	learn: 0.4272530	total: 365ms	remaining: 2.47s
129:	learn: 0.4268545	total: 367ms	remaining: 2.46s
130:	learn: 0.4259613	total: 370ms	remaining: 2.45s
131:	learn: 0.4252709	total: 373ms	remaining: 2.46s
132:	learn: 0.4249394	total: 376ms	remaining: 2.45s
133:	learn: 0.4242581	total: 379ms	remaining: 2.45s
134:	learn: 0.4233835	total: 389ms	remaining: 2.49s
135:	learn: 0.4225679	total: 400ms	remaining: 2.54s
136:	learn: 0.4219773	total: 404ms	remaining: 2.54s
137:	learn: 0.4212240	total: 406ms	remaining: 2.54s
138:	learn: 0.4208694	total: 409ms	remaining: 2.53s
139:	learn: 0.4203034	total: 412ms	remaining: 2.53s
140:	learn: 0.4197989	total: 414ms	remaining: 2.52s
141:	learn: 0.4192886	total: 417ms	remaining: 2.52s
142:	learn: 0.4186604	total: 420ms	remaining: 2.52s
143:	learn: 0.4177568	total: 423ms	remaining: 2.51s
144:	learn: 0.4171348	total: 426ms	remaining: 2.51s
145:	learn: 

293:	learn: 0.3727897	total: 848ms	remaining: 2.04s
294:	learn: 0.3726493	total: 851ms	remaining: 2.03s
295:	learn: 0.3724402	total: 853ms	remaining: 2.03s
296:	learn: 0.3723169	total: 856ms	remaining: 2.02s
297:	learn: 0.3721114	total: 858ms	remaining: 2.02s
298:	learn: 0.3717804	total: 861ms	remaining: 2.02s
299:	learn: 0.3716989	total: 863ms	remaining: 2.01s
300:	learn: 0.3715407	total: 866ms	remaining: 2.01s
301:	learn: 0.3714145	total: 868ms	remaining: 2.01s
302:	learn: 0.3712681	total: 870ms	remaining: 2s
303:	learn: 0.3710532	total: 873ms	remaining: 2s
304:	learn: 0.3708023	total: 875ms	remaining: 1.99s
305:	learn: 0.3706063	total: 877ms	remaining: 1.99s
306:	learn: 0.3704497	total: 880ms	remaining: 1.99s
307:	learn: 0.3703298	total: 882ms	remaining: 1.98s
308:	learn: 0.3701517	total: 884ms	remaining: 1.98s
309:	learn: 0.3700588	total: 886ms	remaining: 1.97s
310:	learn: 0.3698348	total: 888ms	remaining: 1.97s
311:	learn: 0.3696610	total: 891ms	remaining: 1.96s
312:	learn: 0.3695

525:	learn: 0.3389481	total: 1.36s	remaining: 1.23s
526:	learn: 0.3387418	total: 1.37s	remaining: 1.23s
527:	learn: 0.3385941	total: 1.37s	remaining: 1.23s
528:	learn: 0.3384638	total: 1.37s	remaining: 1.22s
529:	learn: 0.3383989	total: 1.38s	remaining: 1.22s
530:	learn: 0.3382253	total: 1.38s	remaining: 1.22s
531:	learn: 0.3381715	total: 1.38s	remaining: 1.21s
532:	learn: 0.3378752	total: 1.38s	remaining: 1.21s
533:	learn: 0.3377747	total: 1.39s	remaining: 1.21s
534:	learn: 0.3376789	total: 1.39s	remaining: 1.21s
535:	learn: 0.3375278	total: 1.39s	remaining: 1.2s
536:	learn: 0.3373241	total: 1.39s	remaining: 1.2s
537:	learn: 0.3370073	total: 1.39s	remaining: 1.2s
538:	learn: 0.3369438	total: 1.4s	remaining: 1.19s
539:	learn: 0.3367811	total: 1.4s	remaining: 1.19s
540:	learn: 0.3367129	total: 1.4s	remaining: 1.19s
541:	learn: 0.3366310	total: 1.4s	remaining: 1.19s
542:	learn: 0.3365823	total: 1.41s	remaining: 1.18s
543:	learn: 0.3363219	total: 1.41s	remaining: 1.18s
544:	learn: 0.33623

744:	learn: 0.3167604	total: 1.88s	remaining: 642ms
745:	learn: 0.3165994	total: 1.88s	remaining: 639ms
746:	learn: 0.3164203	total: 1.88s	remaining: 637ms
747:	learn: 0.3163558	total: 1.88s	remaining: 634ms
748:	learn: 0.3162280	total: 1.88s	remaining: 632ms
749:	learn: 0.3161238	total: 1.89s	remaining: 629ms
750:	learn: 0.3159416	total: 1.89s	remaining: 627ms
751:	learn: 0.3157892	total: 1.89s	remaining: 624ms
752:	learn: 0.3156718	total: 1.9s	remaining: 622ms
753:	learn: 0.3155654	total: 1.9s	remaining: 619ms
754:	learn: 0.3154521	total: 1.9s	remaining: 617ms
755:	learn: 0.3153815	total: 1.9s	remaining: 614ms
756:	learn: 0.3152760	total: 1.91s	remaining: 612ms
757:	learn: 0.3152458	total: 1.91s	remaining: 609ms
758:	learn: 0.3152050	total: 1.91s	remaining: 607ms
759:	learn: 0.3151479	total: 1.91s	remaining: 604ms
760:	learn: 0.3150933	total: 1.92s	remaining: 601ms
761:	learn: 0.3150926	total: 1.92s	remaining: 599ms
762:	learn: 0.3148658	total: 1.92s	remaining: 596ms
763:	learn: 0.31

963:	learn: 0.2942318	total: 2.39s	remaining: 89.2ms
964:	learn: 0.2941374	total: 2.39s	remaining: 86.7ms
965:	learn: 0.2941263	total: 2.39s	remaining: 84.2ms
966:	learn: 0.2937931	total: 2.4s	remaining: 81.8ms
967:	learn: 0.2935076	total: 2.4s	remaining: 79.3ms
968:	learn: 0.2934372	total: 2.4s	remaining: 76.8ms
969:	learn: 0.2934053	total: 2.4s	remaining: 74.3ms
970:	learn: 0.2933347	total: 2.4s	remaining: 71.8ms
971:	learn: 0.2932131	total: 2.41s	remaining: 69.4ms
972:	learn: 0.2930849	total: 2.41s	remaining: 66.9ms
973:	learn: 0.2930662	total: 2.41s	remaining: 64.4ms
974:	learn: 0.2930247	total: 2.41s	remaining: 61.9ms
975:	learn: 0.2929797	total: 2.42s	remaining: 59.4ms
976:	learn: 0.2929270	total: 2.42s	remaining: 56.9ms
977:	learn: 0.2926870	total: 2.42s	remaining: 54.5ms
978:	learn: 0.2925774	total: 2.42s	remaining: 52ms
979:	learn: 0.2925298	total: 2.42s	remaining: 49.5ms
980:	learn: 0.2922138	total: 2.43s	remaining: 47ms
981:	learn: 0.2921807	total: 2.43s	remaining: 44.6ms
98

### 4.11. Predict Test set (with unknown results)

In [53]:
y_pred = classifier.predict(X_pred)

In [54]:
print(y_pred)

[0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


### 4.12. Create result dataframe and print it to csv

In [55]:
print(len(y_pred))

418


In [56]:
result = pd.DataFrame({'PassengerId': test['PassengerId'], 'Survived': y_pred})
print(result)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


In [57]:
result.to_csv('../00_data/catboost.csv', index=False)